quarkus:
  package:
    type: fast-jar
  http:
    cors: true
    port: 18080
  datasource:
    db-kind: h2
    username: vivp
    password: vivp
    jdbc:
      url: jdbc:h2:mem:bankrupt
  hibernate-orm:
    database:
      generation: none
  flyway:
    migrate-at-start: true
mp:
  jwt:
    verify:
      publickey:
        location: META-INF/resources/cert.pem
